# Generated by Django 4.0.4 on 2022-05-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techcollector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techcollector.tech')),
            ],
        ),
    ]
