# Generated by Django 4.0.4 on 2022-05-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcollector', '0002_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='providers',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='tech',
            name='perk',
            field=models.ManyToManyField(to='techcollector.perks'),
        ),
    ]
