# Generated by Django 4.0.4 on 2022-05-24 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techcollector', '0003_perks_alter_providers_options_alter_tech_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
